version: '3.8'
services:
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    restart: always
  springboot-container:
    build: ./backend/spring-boot/spring-boot/   
    depends_on:
      - mysql-container
    ports:
      - 8181:8080
    restart: always
  angular-container:
    build: ./frontend/angular-product-app/
    ports:
      - 81:80
    